### ISSUE TITLE
Error while running "python zazu.py --search"

### ISSUE THREAD

**Issue by smonami** [dataloop-ai/ZazuML#14]
Following README instructions from main page:
Getting error while running:

python zazu.py --search

2020-09-08 16:29:17.693 [ERROR]- dtlpy: Token expired. Please login
2020-09-08 16:29:17.693 [WARNING]- dtlpy.services.cookie: Key not in platform cookie file: check_version_status. Return None
Traceback (most recent call last):
  File "zazu.py", line 2, in <module>
    from launch_pad import Launcher
  File "/root/ZazuML/launch_pad/__init__.py", line 1, in <module>
    from .launcher import Launcher
  File "/root/ZazuML/launch_pad/launcher.py", line 11, in <module>
    from ObjectDetNet.convert2Yolo import convert
ModuleNotFoundError: No module named 'ObjectDetNet.convert2Yolo'

**Comment by NoamRosenberg** [comment]
Hi You're right. That line shouldn't be there. I'm pushing a fix now. Also, a quick local fix would be just delete line 11 from launcher.py
